/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Whitepaper',
      items: [{ type: 'autogenerated', dirName: 'whitepaper' }]
    },
    {
      type: 'category',
      label: 'Admin Handover',
      items: [{ type: 'autogenerated', dirName: 'admin' }]
    },
    {
      type: 'category',
      label: 'Legacy Project Docs',
      items: [{ type: 'autogenerated', dirName: 'legacy' }]
    }
  ]
};

module.exports = sidebars;
